// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: api/user/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	User_OpenCardHandle_FullMethodName    = "/api.user.v1.User/OpenCardHandle"
	User_CardStatusHandle_FullMethodName  = "/api.user.v1.User/CardStatusHandle"
	User_Deposit_FullMethodName           = "/api.user.v1.User/Deposit"
	User_AdminWithdrawEth_FullMethodName  = "/api.user.v1.User/AdminWithdrawEth"
	User_RewardCardTwo_FullMethodName     = "/api.user.v1.User/RewardCardTwo"
	User_AdminRewardList_FullMethodName   = "/api.user.v1.User/AdminRewardList"
	User_AdminUserList_FullMethodName     = "/api.user.v1.User/AdminUserList"
	User_AdminLogin_FullMethodName        = "/api.user.v1.User/AdminLogin"
	User_UpdateCanVip_FullMethodName      = "/api.user.v1.User/UpdateCanVip"
	User_SetVipThree_FullMethodName       = "/api.user.v1.User/SetVipThree"
	User_SetUserCount_FullMethodName      = "/api.user.v1.User/SetUserCount"
	User_AdminConfig_FullMethodName       = "/api.user.v1.User/AdminConfig"
	User_AdminConfigUpdate_FullMethodName = "/api.user.v1.User/AdminConfigUpdate"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// 开卡
	OpenCardHandle(ctx context.Context, in *OpenCardHandleRequest, opts ...grpc.CallOption) (*OpenCardHandleReply, error)
	CardStatusHandle(ctx context.Context, in *CardStatusHandleRequest, opts ...grpc.CallOption) (*CardStatusHandleReply, error)
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositReply, error)
	AdminWithdrawEth(ctx context.Context, in *AdminWithdrawEthRequest, opts ...grpc.CallOption) (*AdminWithdrawEthReply, error)
	RewardCardTwo(ctx context.Context, in *RewardCardTwoRequest, opts ...grpc.CallOption) (*RewardCardTwoReply, error)
	AdminRewardList(ctx context.Context, in *AdminRewardListRequest, opts ...grpc.CallOption) (*AdminRewardListReply, error)
	AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListReply, error)
	AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginReply, error)
	UpdateCanVip(ctx context.Context, in *UpdateCanVipRequest, opts ...grpc.CallOption) (*UpdateCanVipReply, error)
	SetVipThree(ctx context.Context, in *SetVipThreeRequest, opts ...grpc.CallOption) (*SetVipThreeReply, error)
	SetUserCount(ctx context.Context, in *SetUserCountRequest, opts ...grpc.CallOption) (*SetUserCountReply, error)
	AdminConfig(ctx context.Context, in *AdminConfigRequest, opts ...grpc.CallOption) (*AdminConfigReply, error)
	AdminConfigUpdate(ctx context.Context, in *AdminConfigUpdateRequest, opts ...grpc.CallOption) (*AdminConfigUpdateReply, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) OpenCardHandle(ctx context.Context, in *OpenCardHandleRequest, opts ...grpc.CallOption) (*OpenCardHandleReply, error) {
	out := new(OpenCardHandleReply)
	err := c.cc.Invoke(ctx, User_OpenCardHandle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CardStatusHandle(ctx context.Context, in *CardStatusHandleRequest, opts ...grpc.CallOption) (*CardStatusHandleReply, error) {
	out := new(CardStatusHandleReply)
	err := c.cc.Invoke(ctx, User_CardStatusHandle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositReply, error) {
	out := new(DepositReply)
	err := c.cc.Invoke(ctx, User_Deposit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminWithdrawEth(ctx context.Context, in *AdminWithdrawEthRequest, opts ...grpc.CallOption) (*AdminWithdrawEthReply, error) {
	out := new(AdminWithdrawEthReply)
	err := c.cc.Invoke(ctx, User_AdminWithdrawEth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RewardCardTwo(ctx context.Context, in *RewardCardTwoRequest, opts ...grpc.CallOption) (*RewardCardTwoReply, error) {
	out := new(RewardCardTwoReply)
	err := c.cc.Invoke(ctx, User_RewardCardTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminRewardList(ctx context.Context, in *AdminRewardListRequest, opts ...grpc.CallOption) (*AdminRewardListReply, error) {
	out := new(AdminRewardListReply)
	err := c.cc.Invoke(ctx, User_AdminRewardList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListReply, error) {
	out := new(AdminUserListReply)
	err := c.cc.Invoke(ctx, User_AdminUserList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginReply, error) {
	out := new(AdminLoginReply)
	err := c.cc.Invoke(ctx, User_AdminLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateCanVip(ctx context.Context, in *UpdateCanVipRequest, opts ...grpc.CallOption) (*UpdateCanVipReply, error) {
	out := new(UpdateCanVipReply)
	err := c.cc.Invoke(ctx, User_UpdateCanVip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetVipThree(ctx context.Context, in *SetVipThreeRequest, opts ...grpc.CallOption) (*SetVipThreeReply, error) {
	out := new(SetVipThreeReply)
	err := c.cc.Invoke(ctx, User_SetVipThree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetUserCount(ctx context.Context, in *SetUserCountRequest, opts ...grpc.CallOption) (*SetUserCountReply, error) {
	out := new(SetUserCountReply)
	err := c.cc.Invoke(ctx, User_SetUserCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminConfig(ctx context.Context, in *AdminConfigRequest, opts ...grpc.CallOption) (*AdminConfigReply, error) {
	out := new(AdminConfigReply)
	err := c.cc.Invoke(ctx, User_AdminConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AdminConfigUpdate(ctx context.Context, in *AdminConfigUpdateRequest, opts ...grpc.CallOption) (*AdminConfigUpdateReply, error) {
	out := new(AdminConfigUpdateReply)
	err := c.cc.Invoke(ctx, User_AdminConfigUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	// 开卡
	OpenCardHandle(context.Context, *OpenCardHandleRequest) (*OpenCardHandleReply, error)
	CardStatusHandle(context.Context, *CardStatusHandleRequest) (*CardStatusHandleReply, error)
	Deposit(context.Context, *DepositRequest) (*DepositReply, error)
	AdminWithdrawEth(context.Context, *AdminWithdrawEthRequest) (*AdminWithdrawEthReply, error)
	RewardCardTwo(context.Context, *RewardCardTwoRequest) (*RewardCardTwoReply, error)
	AdminRewardList(context.Context, *AdminRewardListRequest) (*AdminRewardListReply, error)
	AdminUserList(context.Context, *AdminUserListRequest) (*AdminUserListReply, error)
	AdminLogin(context.Context, *AdminLoginRequest) (*AdminLoginReply, error)
	UpdateCanVip(context.Context, *UpdateCanVipRequest) (*UpdateCanVipReply, error)
	SetVipThree(context.Context, *SetVipThreeRequest) (*SetVipThreeReply, error)
	SetUserCount(context.Context, *SetUserCountRequest) (*SetUserCountReply, error)
	AdminConfig(context.Context, *AdminConfigRequest) (*AdminConfigReply, error)
	AdminConfigUpdate(context.Context, *AdminConfigUpdateRequest) (*AdminConfigUpdateReply, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) OpenCardHandle(context.Context, *OpenCardHandleRequest) (*OpenCardHandleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenCardHandle not implemented")
}
func (UnimplementedUserServer) CardStatusHandle(context.Context, *CardStatusHandleRequest) (*CardStatusHandleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CardStatusHandle not implemented")
}
func (UnimplementedUserServer) Deposit(context.Context, *DepositRequest) (*DepositReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedUserServer) AdminWithdrawEth(context.Context, *AdminWithdrawEthRequest) (*AdminWithdrawEthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminWithdrawEth not implemented")
}
func (UnimplementedUserServer) RewardCardTwo(context.Context, *RewardCardTwoRequest) (*RewardCardTwoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardCardTwo not implemented")
}
func (UnimplementedUserServer) AdminRewardList(context.Context, *AdminRewardListRequest) (*AdminRewardListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRewardList not implemented")
}
func (UnimplementedUserServer) AdminUserList(context.Context, *AdminUserListRequest) (*AdminUserListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserList not implemented")
}
func (UnimplementedUserServer) AdminLogin(context.Context, *AdminLoginRequest) (*AdminLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedUserServer) UpdateCanVip(context.Context, *UpdateCanVipRequest) (*UpdateCanVipReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCanVip not implemented")
}
func (UnimplementedUserServer) SetVipThree(context.Context, *SetVipThreeRequest) (*SetVipThreeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVipThree not implemented")
}
func (UnimplementedUserServer) SetUserCount(context.Context, *SetUserCountRequest) (*SetUserCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserCount not implemented")
}
func (UnimplementedUserServer) AdminConfig(context.Context, *AdminConfigRequest) (*AdminConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminConfig not implemented")
}
func (UnimplementedUserServer) AdminConfigUpdate(context.Context, *AdminConfigUpdateRequest) (*AdminConfigUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminConfigUpdate not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_OpenCardHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenCardHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).OpenCardHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_OpenCardHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).OpenCardHandle(ctx, req.(*OpenCardHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CardStatusHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardStatusHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CardStatusHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CardStatusHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CardStatusHandle(ctx, req.(*CardStatusHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminWithdrawEth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminWithdrawEthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminWithdrawEth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminWithdrawEth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminWithdrawEth(ctx, req.(*AdminWithdrawEthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RewardCardTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewardCardTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RewardCardTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_RewardCardTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RewardCardTwo(ctx, req.(*RewardCardTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminRewardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRewardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminRewardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminRewardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminRewardList(ctx, req.(*AdminRewardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminUserList(ctx, req.(*AdminUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminLogin(ctx, req.(*AdminLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateCanVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCanVipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateCanVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateCanVip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateCanVip(ctx, req.(*UpdateCanVipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetVipThree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVipThreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetVipThree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetVipThree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetVipThree(ctx, req.(*SetVipThreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetUserCount(ctx, req.(*SetUserCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminConfig(ctx, req.(*AdminConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AdminConfigUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AdminConfigUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AdminConfigUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AdminConfigUpdate(ctx, req.(*AdminConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenCardHandle",
			Handler:    _User_OpenCardHandle_Handler,
		},
		{
			MethodName: "CardStatusHandle",
			Handler:    _User_CardStatusHandle_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _User_Deposit_Handler,
		},
		{
			MethodName: "AdminWithdrawEth",
			Handler:    _User_AdminWithdrawEth_Handler,
		},
		{
			MethodName: "RewardCardTwo",
			Handler:    _User_RewardCardTwo_Handler,
		},
		{
			MethodName: "AdminRewardList",
			Handler:    _User_AdminRewardList_Handler,
		},
		{
			MethodName: "AdminUserList",
			Handler:    _User_AdminUserList_Handler,
		},
		{
			MethodName: "AdminLogin",
			Handler:    _User_AdminLogin_Handler,
		},
		{
			MethodName: "UpdateCanVip",
			Handler:    _User_UpdateCanVip_Handler,
		},
		{
			MethodName: "SetVipThree",
			Handler:    _User_SetVipThree_Handler,
		},
		{
			MethodName: "SetUserCount",
			Handler:    _User_SetUserCount_Handler,
		},
		{
			MethodName: "AdminConfig",
			Handler:    _User_AdminConfig_Handler,
		},
		{
			MethodName: "AdminConfigUpdate",
			Handler:    _User_AdminConfigUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/user.proto",
}
